### PR TITLE
TCP Connect timeout and more events

### PR DESCRIPTION
**Pull request by markterrill**
Relies on https://github.com/cesanta/mongoose-os/pull/561 for the matching event enum

### CODE REVIEW

**Comment by markterrill** [comment]
Also this PR includes a new flag: mqtt.debug_use_log_level
Before it was publishing events with the log_level field set effective to boolean of was it std_out or std_error?
This means upstream it loses visibility of debug/info/warning etc.
I have implemented it via a new flag that defaults to false so it's not a breaking change. However to me it seems very useful, it means the logs I'm transferring over to GCP log events are correctly tagged with their original log level. Very very useful.

**Comment by markterrill** [comment]
Have created a documentation PR as well
https://github.com/cesanta/mongoose-os-docs/pull/45

**Comment by rojer** [comment]
i understand the idea, and i think we should use the same logging format as used by UDP logging, here: https://github.com/cesanta/mongoose-os/blob/2779f2d448e272b72342d5a60d62af425f52ba65/src/mgos_debug.c#L86-L118

pull it out into a function and reuse.

**Comment by markterrill** [comment]
> i understand the idea, and i think we should use the same logging format as used by UDP logging, here: https://github.com/cesanta/mongoose-os/blob/2779f2d448e272b72342d5a60d62af425f52ba65/src/mgos_debug.c#L86-L118
> 
> pull it out into a function and reuse.

I'm honestly not sure what those referenced lines are doing.

My PR simply replaces the primitive out/err that's being used as the log level with the actual log level.

**Comment by markterrill** [comment]
At best I understand that the UDP lines you referenced are creating a string with current time and log level as a string, ie DEBUG. I apologise but it's beyond my limited C hacker skills to know what to do with those bufs and rewrite the existing log function. I can't spot where the actual log line is being appended!

**Comment by markterrill** [comment]
@rojer If you'd like to change the function to reflect other parts of the system that's cool. However my PR significantly improves the usefulness of the existing format with no breaking changes - aside from understanding you're now getting a cs_log_level value instead of an apparently meaningless fd number that isn't consistent. I'd like it to be accepted and if someone wants to change it to the udp function then they can have at it.

**Pull request closed without merging**
