### PR TITLE
Remove implicit reconnect in mgos_mqtt_sub() 

### PR DESCRIPTION
**Pull request by guglielmino**
Reconnect behavior must be explicit for the user

### CODE REVIEW

**Comment by cpq** [comment]
Did you actually test it?
Does client subscribe as intended without the reconnect?

**Comment by guglielmino** [comment]
Yes, I did a test linking my local repository and, in my use cases, it works as expected.

**Comment by cpq** [comment]
global subscribe does not actually send mqtt subscribe command anywhere.
it just registers a handler:

https://github.com/guglielmino/mqtt/blob/fa661e6a05f051e2e1f0c45ddb026d85254edb46/src/mgos_mqtt.c#L185-L195

The actual subscription is done when the CONNACK received:
https://github.com/guglielmino/mqtt/blob/fa661e6a05f051e2e1f0c45ddb026d85254edb46/src/mgos_mqtt.c#L140

**Comment by guglielmino** [comment]
This is strange because I'm doing some tests and it just works fine. Try yourself using [https://github.com/guglielmino/mqtt/tree/no-implicit-reconnect-on-subscribe](https://github.com/guglielmino/mqtt/tree/no-implicit-reconnect-on-subscribe). 

Are you sure subscription is handled only on CONNACK? 

Anyhow, require that a subscription can be done ONLY on CONNACK is not a good thing, it is also against on how MQTT works.

**Pull request closed without merging**
